apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
stringData:
  slack-token: "xoxb-your-slack-bot-token"
  discord-webhook-url: "https://discord.com/api/webhooks/your-webhook-url"
  email-username: "your-email@gmail.com"
  email-password: "your-app-password"