alertmanager:
  config:
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'techlekedev@gmail.com'
      smtp_auth_username: 'techlekedev@gmail.com'
      smtp_auth_password: 'your-app-password'
      smtp_require_tls: true
    route:
      group_by: ['alertname', 'job', 'severity']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: 'email-notifications'
    receivers:
    - name: 'email-notifications'
      email_configs:
      - to: 'techlekedev@gmail.com'
        send_resolved: true
    - name: 'null'