apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  template:
    spec:
      priorityClassName: high-priority
      containers:
      - name: app
        image: ghcr.io/your-org/sample-app:latest