apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    domain = grafana.example.com
    root_url = %(protocol)s://%(domain)s:/grafana
    
    [auth.anonymous]
    enabled = true
    org_role = Viewer
    
    [users]
    allow_sign_up = false
    auto_assign_org = true
    auto_assign_org_role = Viewer
    
    [dashboards]
    versions_to_keep = 20
    
    [log]
    mode = console
    
    [metrics]
    enabled = true
    interval_seconds = 10