apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-test
  namespace: testing
spec:
  template:
    metadata:
      labels:
        app: k6
    spec:
      containers:
      - name: k6
        image: grafana/k6:latest
        command: ['k6', 'run', '--out', 'influxdb=http://influxdb:8086/k6', '/scripts/basic-load-test.js']
        env:
        - name: BASE_URL
          value: "http://sample-app.production.svc.cluster.local"
        - name: K6_VUS
          value: "100"
        - name: K6_DURATION
          value: "5m"
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
      restartPolicy: Never
      volumes:
      - name: scripts
        configMap:
          name: k6-scripts
  backoffLimit: 4