{
 "title": "Istio Service Mesh",
 "tags": [
  "istio",
  "service-mesh"
 ],
 "refresh": "25s",
 "panels": [
  {
   "title": "Request Volume",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total[5m])) by (destination_service)",
     "legendFormat": "{{destination_service}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket[5m])) by (destination_service, le))",
     "legendFormat": "{{destination_service}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "singlestat",
   "gridPos": { "x": 0, "y": 9, "w": 6, "h": 3 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total[5m]))"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "singlestat",
   "gridPos": { "x": 6, "y": 9, "w": 6, "h": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{response_code=~\"5.*\"}[5m])) / sum(rate(istio_requests_total[5m]))"
    }
   ]
  },
  {
   "title": "Traffic by Response Code",
   "type": "graph",
   "gridPos": { "x": 12, "y": 9, "w": 12, "h": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total[5m])) by (response_code)",
     "legendFormat": "{{response_code}}"
    }
   ]
  }
 ]
}