{
 "title": "K6 Load Testing",
 "tags": [
  "k6",
  "load-testing"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Request Rate",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(k6_http_reqs_total[5m]))",
     "legendFormat": "Requests per second"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(k6_http_req_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(k6_http_req_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Virtual Users",
   "type": "singlestat",
   "gridPos": { "x": 0, "y": 9, "w": 6, "h": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "k6_vus" }
   ]
  },
  {
   "title": "HTTP Request Failed",
   "type": "singlestat",
   "gridPos": { "x": 6, "y": 9, "w": 6, "h": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(k6_http_req_failed_total[5m]))"
    }
   ]
  },
  {
   "title": "Data Transfer",
   "type": "graph",
   "gridPos": { "x": 12, "y": 9, "w": 12, "h": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(k6_data_sent_total[5m]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(rate(k6_data_received_total[5m]))",
     "legendFormat": "Received"
    }
   ]
  }
 ]
}