{
 "title": "Kubernetes Dashboard",
 "tags": [ "kubernetes" ],
 "refresh": "25s",
 "panels": [
  {
   "title": "Pod CPU Usage",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod!=\"\", container!=\"POD\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod!=\"\", container!=\"POD\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "x": 0, "y": 9, "w": 6, "h": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "title": "Pods",
   "type": "singlestat",
   "gridPos": { "x": 6, "y": 9, "w": 6, "h": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(kube_pod_info)" }
   ]
  },
  {
   "title": "Deployments",
   "type": "singlestat",
   "gridPos": { "x": 12, "y": 9, "w": 6, "h": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_deployment_status_replicas)"
    }
   ]
  },
  {
   "title": "Services",
   "type": "singlestat",
   "gridPos": { "x": 18, "y": 9, "w": 6, "h": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(kube_service_info)" }
   ]
  }
 ]
}