apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-advanced-rules
  namespace: monitoring
data:
  advanced-rules.yml: |
    groups:
      - name: application_slo_alerts
        interval: 30s
        rules:
          # SLO: 99.9% availability
          - alert: SLOViolation999
            expr: |
              (
                sum(rate(http_requests_total{status!~"5.."}[5m])) /
                sum(rate(http_requests_total[5m]))
              ) < 0.999
            for: 5m
            labels:
              severity: critical
              slo: "99.9"
            annotations:
              summary: "SLO violation: availability below 99.9%"
              description: "Current availability is {{ $value | humanizePercentage }} which is below our 99.9% SLO"
          
          # High latency P95
          - alert: HighLatencyP95
            expr: |
              histogram_quantile(0.95,
                rate(http_request_duration_seconds_bucket[5m])
              ) > 1.0
            for: 10m
            labels:
              severity: warning
            annotations:
              summary: "High request latency (P95)"
              description: "95th percentile latency is {{ $value }}s (threshold: 1s)"
          
          # High latency P99
          - alert: HighLatencyP99
            expr: |
              histogram_quantile(0.99,
                rate(http_request_duration_seconds_bucket[5m])
              ) > 2.0
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Critical request latency (P99)"
              description: "99th percentile latency is {{ $value }}s (threshold: 2s)"
          
          # Abnormal traffic spike
          - alert: TrafficSpike
            expr: |
              rate(http_requests_total[5m]) >
              (
                avg_over_time(rate(http_requests_total[5m])[1h:5m]) +
                (2 * stddev_over_time(rate(http_requests_total[5m])[1h:5m]))
              )
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "Traffic spike detected"
              description: "Request rate has increased significantly above normal (current: {{ $value }})"
          
          # Error rate threshold
          - alert: HighErrorRate
            expr: |
              rate(http_requests_total{status=~"5.."}[5m]) /
              rate(http_requests_total[5m]) > 0.01
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "High error rate"
              description: "Error rate is {{ $value | humanizePercentage }} (threshold: 1%)"
          
          # Memory usage
          - alert: HighMemoryUsage
            expr: |
              container_memory_usage_bytes{container!="POD",container!=""} /
              container_spec_memory_limit_bytes{container!="POD",container!=""} > 0.85
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High memory usage"
              description: "Container memory usage is {{ $value | humanizePercentage }} (threshold: 85%)"
          
          # CPU usage
          - alert: HighCPUUsage
            expr: |
              rate(container_cpu_usage_seconds_total{container!="POD",container!=""}[5m]) /
              container_spec_cpu_quota{container!="POD",container!=""} > 0.85
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High CPU usage"
              description: "Container CPU usage is {{ $value | humanizePercentage }} (threshold: 85%)"
          
          # Disk space
          - alert: LowDiskSpace
            expr: |
              (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.1
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Low disk space"
              description: "Disk space is {{ $value | humanizePercentage }} available (threshold: 10%)"
          
          # Kubernetes pod crash loop
          - alert: PodCrashLooping
            expr: |
              rate(kube_pod_container_status_restarts_total[5m]) > 0.1
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Pod crash looping"
              description: "Pod {{ $labels.pod }} is restarting frequently ({{ $value }})"
          
          # Kubernetes node not ready
          - alert: NodeNotReady
            expr: |
              kube_node_status_condition{condition="Ready",status="false"} == 1
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Node not ready"
              description: "Node {{ $labels.node }} is not ready"