apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  alert-rules.yml: |
    groups:
      - name: application_alerts
        interval: 30s
        rules:
          - alert: HighErrorRate
            expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "High error rate detected"
              description: "Error rate is {{ $value }} for {{ $labels.instance }}"
          
          - alert: HighMemoryUsage
            expr: container_memory_usage_bytes{container!="POD",container!=""} > 500000000
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High memory usage detected"
              description: "Container memory usage is {{ $value }} for {{ $labels.container }}"
          
          - alert: HighCPULoad
            expr: rate(container_cpu_usage_seconds_total{container!="POD",container!=""}[5m]) > 0.8
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High CPU load detected"
              description: "Container CPU usage is {{ $value }} for {{ $labels.container }}"
          
          - alert: ServiceDown
            expr: up == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Service is down"
              description: "Service {{ $labels.job }} is down"