{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "sample-app.fullname" . }}
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "sample-app.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "sample-app.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - {}
{{- end }}