apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

bases:
  - ../../base

replicas:
  - name: sample-app
    count: 1

images:
  - name: leke1995/sample-app
    newTag: dev-latest

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "64Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "128Mi"
    target:
      kind: Deployment
      name: sample-app